# Generated by Django 2.1.7 on 2019-04-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(max_length=255, upload_to='partners'),
        ),
    ]
