# Generated by Django 2.1.7 on 2019-04-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
    ]
