# Generated by Django 3.0.6 on 2020-05-17 02:11

import ckeditor.fields
from django.db import migrations, models
import linguist.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description_az', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('icon', models.CharField(default='Null', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sub service',
                'verbose_name_plural': 'sub services',
            },
            bases=(linguist.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sub_title_az', models.TextField(blank=True, null=True)),
                ('sub_title_en', models.TextField(blank=True, null=True)),
                ('sub_title_ru', models.TextField(blank=True, null=True)),
                ('short_description_az', models.TextField(null=True)),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_ru', models.TextField(null=True)),
                ('description_az', ckeditor.fields.RichTextField(null=True)),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(upload_to='service')),
                ('image_description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, default=0)),
                ('home', models.BooleanField(default=False, verbose_name='Display at home')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('sub_service', models.ManyToManyField(blank=True, to='services.SubService')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
            bases=(linguist.mixins.ModelMixin, models.Model),
        ),
    ]
