# Generated by Django 2.1.7 on 2019-03-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190328_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
