# Generated by Django 2.1.7 on 2019-03-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190328_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='text_az',
        ),
        migrations.RemoveField(
            model_name='service',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='text_ru',
        ),
    ]
