# Generated by Django 2.1.7 on 2019-04-02 06:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import linguist.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190401_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description_az', ckeditor.fields.RichTextField(null=True)),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'verbose_name': 'sub service',
                'verbose_name_plural': 'sub services',
            },
            bases=(linguist.mixins.ModelMixin, models.Model),
        ),
    ]
