# Generated by Django 2.1.7 on 2019-04-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_subservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='sub_service',
            field=models.ManyToManyField(to='services.SubService'),
        ),
    ]
