# Generated by Django 2.1.7 on 2019-04-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20190402_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
