# Generated by Django 2.1.7 on 2019-04-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20190402_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='short_description_az',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
