# Generated by Django 2.1.7 on 2019-04-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20190402_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sub_title_az',
            field=models.TextField(blank=True, null=True),
        ),
    ]
