# Generated by Django 2.1.7 on 2019-04-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20190402_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
