# Generated by Django 2.1.7 on 2019-04-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_service_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='home',
            field=models.BooleanField(default=False, verbose_name='Display at home'),
        ),
    ]
