# Generated by Django 2.1.7 on 2019-04-05 08:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190405_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
