# Generated by Django 3.0.6 on 2020-05-17 02:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import linguist.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('body_az', ckeditor.fields.RichTextField(null=True)),
                ('body_en', ckeditor.fields.RichTextField(null=True)),
                ('body_ru', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='portfolio')),
                ('image_back', models.ImageField(max_length=255, null=True, upload_to='portfolio')),
                ('url', models.CharField(blank=True, max_length=255)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.IntegerField(blank=True)),
                ('home', models.BooleanField(default=False, verbose_name='Display at home')),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolios',
            },
            bases=(linguist.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'portfolio category',
                'verbose_name_plural': 'portfolio categories',
            },
            bases=(linguist.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='portfolio')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioCategory'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='services',
            field=models.ManyToManyField(to='services.Service'),
        ),
    ]
