# Generated by Django 2.1.7 on 2019-03-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
