# Generated by Django 2.1.7 on 2019-03-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190329_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='body_az',
            field=models.TextField(null=True),
        ),
    ]
