# Generated by Django 2.1.7 on 2019-03-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190329_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
