# Generated by Django 2.1.7 on 2019-04-02 08:14

from django.db import migrations, models
import django.db.models.deletion
import linguist.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20190329_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('slug_az', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'portfolio category',
                'verbose_name_plural': 'portfolio categories',
            },
            bases=(linguist.mixins.ModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug_az',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioCategory'),
            preserve_default=False,
        ),
    ]
