# Generated by Django 2.1.7 on 2019-04-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20190402_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug_az',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
