# Generated by Django 2.1.7 on 2019-04-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190402_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='slug_az',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='slug_ru',
        ),
    ]
