# Generated by Django 2.1.7 on 2019-04-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20190402_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='portfolio'),
        ),
    ]
