# Generated by Django 2.1.7 on 2019-04-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_portfolio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
