# Generated by Django 2.1.7 on 2019-04-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_portfolio_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
