# Generated by Django 2.1.7 on 2019-04-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20190409_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_back',
            field=models.ImageField(max_length=255, null=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='position',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioimages',
            name='portfolio',
            field=models.ForeignKey(on_delete='CASCADE', to='portfolio.Portfolio'),
        ),
    ]
