# Generated by Django 2.1.7 on 2019-04-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20190409_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='home',
            field=models.BooleanField(default=False, verbose_name='Display at home'),
        ),
    ]
